# PDA_BCD (block-coordinate discretized action optimization)
exp_name: "pda_bcd"
agent_name: "PDA_BCD"
seed: 0
torch_deterministic: false
device: "cpu"
logging: true

env_id: "HalfCheetah-v4"

env_kargs: null

total_timesteps: 1000000
learning_rate: 0.001
num_envs: 10
num_test_envs: 10
test_interval: 5
num_steps: 400
anneal_lr: false
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 10
hidden_sizes: [64, 64]
obs_norm: true
max_grad_norm: 0.5
ret_norm: true
adv_norm: true
recompute_ret: true

step_size: 0.9
act_noise: 0.5
action_opt_itr: 75
discretization: 16
